Feat/profil interface
ilyasmirnov03/flame-game pull request #30
Opened 2024-03-05 15:44 UTC by mchauveni

2024-03-05 20:57 UTC, ilyasmirnov03 requested changes

2024-03-05 20:57 UTC, ilyasmirnov03 commented on routes/web.php
> +    })->name("profile")->middleware(['auth']);
Peut etre renommer la route a 'index' pour eviter le 'profile.profile'? Idem pour le fichier de vue dcp

2024-03-05 20:57 UTC, ilyasmirnov03 commented on routes/web.php
> +        $user = DB::table('users')->find($userId);
tu peux mettre function (User $user) directement dans la route et laravel va lier l'id a la table User

2024-03-06 10:14 UTC, mchauveni commented on routes/web.php
> +    })->name("profile")->middleware(['auth']);
j'ai suivit l'exemple de flame.flame pour ça, mais j'peux modifier quand même si tu préfère

2024-03-06 10:18 UTC, mchauveni commented on routes/web.php
> +        $user = DB::table('users')->find($userId);
ça m'éxecute ce statement : 
```select * from `users` where `id` = 101 limit 1```

peu importe l'id du user.
Le code utilisé : 
```
    Route::get('/{userId}', function (User $user) {
        return view('profile.profile', ['user' => $user]);
    })->name("consult");
```

2024-03-06 10:58 UTC, ilyasmirnov03 commented on routes/web.php
> +    })->name("profile")->middleware(['auth']);
Oui mais faut changer ce flame.flame aussi :D

2024-03-06 11:07 UTC, mchauveni commented on routes/web.php
> +    })->name("profile")->middleware(['auth']);
je change les deux

2024-03-06 11:08 UTC, mchauveni commented on routes/web.php
> +        $user = DB::table('users')->find($userId);
bien vu

2024-03-06 11:15 UTC, ilyasmirnov03 requested changes

2024-03-06 11:15 UTC, ilyasmirnov03 commented on routes/web.php
> +use Illuminate\Support\Facades\DB;
use a enlever

2024-03-06 12:27 UTC, ilyasmirnov03 approved these changes

2024-03-06 12:27 UTC, merged