Feat/game UI
ilyasmirnov03/flame-game pull request #8
Opened 2024-02-12 11:04 UTC by PMulx

2024-02-12 12:29 UTC, ilyasmirnov03 reviewed
Pour l'instant c'est bon, par contre il y a une erreur dans la console a chauque fois qu'on rafraichit la page sauf pour la page des params. C'est parce qu'on fait un query selector d'un element qui n'existe pas. Je suggere de load le fichier params.js que sur la page de params

2024-02-12 12:29 UTC, ilyasmirnov03 commented on resources/views/flamme_indiv.blade.php
> +<!DOCTYPE html>
Ca veut dire quoi "indiv" ?

2024-02-13 13:38 UTC, PMulx commented on resources/views/flamme_indiv.blade.php
> +<!DOCTYPE html>
Individuel genre ta flamme perso

2024-02-13 15:39 UTC, ilyasmirnov03 requested changes

2024-02-13 15:39 UTC, ilyasmirnov03 commented on config/minigames.php
> +<?php
Met le plutot dans le fichier static.php avec la cle "minigames" qui va contenir ces minigames la

2024-02-13 15:39 UTC, ilyasmirnov03 commented on app/Providers/AppServiceProvider.php
>  namespace App\Providers;
Pas besion (voir les autres commentaires)

2024-02-13 15:39 UTC, ilyasmirnov03 commented on routes/web.php
> +    if (!array_key_exists($game, Config::get('minigames'))) {
Avec le changement suggere au dessus, tu pourras juste appeler config('static.minigames')

2024-02-13 15:39 UTC, ilyasmirnov03 commented on resources/views/flamme_indiv.blade.php
> +<!DOCTYPE html>
Renomme le plutot au solo_flame ou individual_flame pour rester en anglais pour les noms de fichiers

2024-02-13 15:39 UTC, ilyasmirnov03 commented on resources/js/params.js
> +    if (resetButton) {
Tu peux faire resetButton?.addEventListener() au lieu des if

2024-02-13 15:39 UTC, ilyasmirnov03 commented on resources/js/params.js
> +        if (fontSizeElement) {
Si un de ces elements n'existe pas, c'est que les autres n'existent pas non plus. Donc en haut de la fonction tu peux faire if (!fontSizeElement) { return; } pour arreter l'execution tout en haut si l'element n'existe pas

2024-02-13 15:39 UTC, ilyasmirnov03 commented on resources/js/params.js
> +        if (fontSizeElement) {
Comme ca pas besoin des if a chaque fois

2024-02-13 16:00 UTC, ilyasmirnov03 approved these changes

2024-02-13 16:01 UTC, merged